/*
データベース構築　DDL文 
クラス：IE2A01
制作者：山田　太郎
作成日：2021/04/01
*/

/*---------------テーブル作成----------------------*/
-- 値引区分
CREATE TABLE REDUCTION(
    CLASS INT,
    RNAME VARCHAR(10) NOT NULL,
    PRIMARY KEY(CLASS)
);

-- 引渡区分
CREATE TABLE DELIVERY(
    CLASS INT,
    DNAME VARCHAR(10) NOT NULL,
    PRIMARY KEY(CLASS)
);

-- 支払区分
CREATE TABLE PAYMENT(
    CLASS INT,
    PNAME VARCHAR(10) NOT NULL,
    PRIMARY KEY(CLASS)
);

-- キャンペーン表
CREATE TABLE CAMPAIGN(
    CAMP_CODE CHAR(4),
    EXP_TEXT VARCHAR(256) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    COUPON_NAME VARCHAR(50) NOT NULL,
    RED_CLASS INT NOT NULL,
    RED_VALUE INT NOT NULL,
    USE_PERIOD DATE NOT NULL,
    VALID_COUNT INT NOT NULL,
    APPLY_MONEY INT NOT NULL,
    PRIMARY KEY(CAMP_CODE),
    FOREIGN KEY(RED_CLASS) REFERENCES REDUCTION(CLASS)
);

-- 顧客表
CREATE TABLE USER(
    USER_NO INT AUTO_INCREMENT,
    UNAME VARCHAR(20) NOT NULL,
    RUBY VARCHAR(60) NOT NULL,
    MAIL VARCHAR(256) NOT NULL UNIQUE,
    PASSWORD CHAR(255) NOT NULL,
    TEL VARCHAR(10) NOT NULL UNIQUE,
    CARD_NO CHAR(16) UNIQUE,
    PRIMARY KEY(USER_NO)
);

-- お届け先表
CREATE TABLE DELIADDRESS(
    USER_NO INT,
    DELI_NO INT,
    POST_NO INT NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    PRIMARY KEY(USER_NO, DELI_NO),
    FOREIGN KEY(USER_NO) REFERENCES USER(USER_NO)
);

-- 保有クーポン表
CREATE TABLE OWNEDCP(
    USER_NO INT,
    CAMP_CODE CHAR(4),
    COUPON_NAME VARCHAR(50),
    RED_CLASS INT,
    RED_VALUE INT,
    USE_PERIOD DATE,
    REMAIN_COUNT INT,
    PRIMARY KEY(USER_NO, CAMP_CODE),
    FOREIGN KEY(USER_NO) REFERENCES USER(USER_NO),
    FOREIGN KEY(CAMP_CODE) REFERENCES CAMPAIGN(CAMP_CODE),
    FOREIGN KEY(RED_CLASS) REFERENCES REDUCTION(CLASS)
);

-- 受注ヘッダ表
CREATE TABLE ORDERHEADER(
    ODR_NO INT auto_increment,
    ODR_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EMP_NO CHAR(5),
    STORE_NO CHAR(3),
    USER_NO INT,
    UNAME VARCHAR(20),
    TEL VARCHAR(10),
    POST_NO INT,
    ADDRESS VARCHAR(100),
    CAMP_CODE CHAR(4),
    COUPON_NAME VARCHAR(50),
    USE_PERIOD DATE,
    DELI_CLASS INT,
    PAY_CLASS INT,
    TAX INT NOT NULL,
    APPLY_CAMP_CODE CHAR(4),
    APPLY_COUPON_NAME VARCHAR(50),
    APPLY_USE_PERIOD DATE,
    APPLY_VALID_COUNT INT,
    PRIMARY KEY(ODR_NO),
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    FOREIGN KEY(STORE_NO) REFERENCES STORE(STORE_NO),
    FOREIGN KEY(USER_NO) REFERENCES USER(USER_NO),
    FOREIGN KEY(DELI_CLASS) REFERENCES DELIVERY(CLASS),
    FOREIGN KEY(PAY_CLASS) REFERENCES PAYMENT(CLASS),
    FOREIGN KEY(APPLY_CAMP_CODE) REFERENCES OWNEDCP(CAMP_CODE)
);

-- 受注明細表
CREATE TABLE ORDERDETAIL(
    ODR_NO INT,
    DET_NO INT,
    PRODUCT_NO CHAR(4),
    PNAME VARCHAR(50),
    CATEGORY CHAR(4),
    SIZE CHAR(1),
    PRICE INT,
    QTY INT,
    PRIMARY KEY(ODR_NO, DET_NO),
    FOREIGN KEY(ODR_NO) REFERENCES ORDERHEADER(ODR_NO),
    FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)
);

/*---------------------データ挿入---------------------------*/
-- 区分データ登録
INSERT INTO REDUCTION (CLASS, RNAME) VALUES (1, '金額値引');
INSERT INTO REDUCTION (CLASS, RNAME) VALUES (2, '％値引');
INSERT INTO DELIVERY (CLASS, DNAME) VALUES (1, '受取');
INSERT INTO DELIVERY (CLASS, DNAME) VALUES (2, '配達');
INSERT INTO PAYMENT (CLASS, PNAME) VALUES (1, '現金');
INSERT INTO PAYMENT (CLASS, PNAME) VALUES (2, 'カード');

-- データ確定
COMMIT;

-- テーブル構造の確認
DESCRIBE REDUCTION;
DESCRIBE DELIVERY;
DESCRIBE PAYMENT;
DESCRIBE CAMPAIGN;
DESCRIBE USER;
DESCRIBE DELIADDRESS;
DESCRIBE OWNEDCP;
DESCRIBE ORDERHEADER;
DESCRIBE ORDERDETAIL;
