use studb;

drop table OLDPRODUCT;

-- 旧商品表(森修正 主キー追加　商品コードと価格にチェック制約を付加　全ての項目をNOTNULL指定)
CREATE TABLE `studb`.`oldproduct` (
  `PRODUCT_NO` CHAR(4) NOT NULL,
  `PNAME` VARCHAR(50) NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_NO`),
  CONSTRAINT `PRODUCT_NO` CHECK (regexp_like(`PRODUCT_NO`,_utf8mb4'^[0-9]{4}$')),
  CONSTRAINT `PRICE` CHECK (((0 <= `PRICE`) and (`PRICE` <= 10000)))
);

-- 旧商品表
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('0901','エビマヨネーズ','ピザ',1600);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('0902','アスパラベーコン','ピザ',1800);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('2901','ビール','ドリンク',500);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('2902','レモンチューハイ','ドリンク',350);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('2903','ウイスキー','ドリンク',3400);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('2904','100%アップルジュース','ドリンク',400);
INSERT INTO OLDPRODUCT(PRODUCT_NO, PNAME, CATEGORY, PRICE)
VALUES ('2905','１００％オレンジジュース','ドリンク',400);

COMMIT;

SELECT * FROM OLDPRODUCT;

SHOW COLUMNS FROM OLDPRODUCT;

-- チェック制約の確認
SELECT * FROM information_schema.check_constraints;