-- ユーザ作成(User名：oda)
DROP USER IF EXISTS oda;
CREATE USER oda IDENTIFIED WITH MYSQL_NATIVE_PASSWORD BY 'taka';

-- データベース作成
CREATE DATABASE SM;

-- ユーザにデータベース権限付与
GRANT ALL ON SM.* TO oda;

USE SM;

CREATE TABLE USER (
    ID VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(30),
    MAIL_ADDRESS VARCHAR(50),
    NAME VARCHAR(50),
    HOURLY_WAGE INT
);

CREATE TABLE WISH_LIST (
    PNumber INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50),
    PRODUCT VARCHAR(255),
    PRICE INT,
    VISIBLE BOOLEAN DEFAULT FALSE,
    LINK VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE HOUSEHOLD_ACCOUNT_BOOK (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    COST VARCHAR(65),
    RATIO DECIMAL(65)
);

CREATE TABLE DEPOSIT (
    DNumber INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50),
    AMOUNT INT,
    TARGET_AMOUNT INT,
    LIMIT_AMOUNT INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE hourly_wage (
    id INT PRIMARY KEY AUTO_INCREMENT,
    wage DECIMAL(65) -- 時給を格納するカラム
);

--給料履歴
CREATE TABLE INCOME (
    INumber INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50),
    CONTENTS VARCHAR(20),
    SALARY INT,
    DATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

ALTER TABLE INCOME MODIFY COLUMN DATE DATETIME;

--支出履歴
CREATE TABLE SPENDING (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE DATE, 
    USER_ID VARCHAR(50), 
    BUYPRODUCT VARCHAR(255), 
    PRICE INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);


--固定支出履歴
CREATE TABLE fixed_spending (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(20),
    fixed_expenses VARCHAR(255) NOT NULL,
    price INT,
    start_date DATE NOT NULL,
    next_due_date DATE NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USER(ID)
);

ALTER TABLE USER MODIFY COLUMN PASSWORD VARCHAR(255);

ALTER TABLE SPENDING MODIFY COLUMN DATE DATETIME;
ALTER TABLE FIXED_SPENDING MODIFY COLUMN DATE DATETIME;

ALTER TABLE HOUSEHOLD_ACCOUNT_BOOK MODIFY COLUMN date DATETIME;

INSERT INTO USER(ID,PASSWORD,MAIL_ADDRESS,NAME)
VALUES ('1111','1111','aaa@ecc.ac.jp','あああ');

INSERT INTO DEPOSIT(AMOUNT, TARGET_AMOUNT, LIMIT_AMOUNT)
VALUES (10000, 100000000, 1000000);

INSERT INTO WISH_LIST (PRODUCT, PRICE)
VALUES ('モニター',20000);

INSERT INTO WISH_LIST (PRODUCT, PRICE)
VALUES ('マウス',5000);

INSERT INTO WISH_LIST (PRODUCT, PRICE)
VALUES ('マウスパッド',3000);

INSERT INTO WISH_LIST (PRODUCT, PRICE)
VALUES ('マイク',10000);

INSERT INTO
	SPENDING(DATE,BUYPRODUCT,PRICE)
	VALUES(
	'2023-12-22 12:12:12',
    '0',
    '250000'
	);

    INSERT INTO
	FIXED_SPENDING(DATE,FIXED_EXPENSES,PRICE)
	VALUES(
	'2024-06-22 18:15:12',
    '家賃',
    '320000'
	);

INSERT INTO
	HOUSEHOLD_ACCOUNT_BOOK(COST,RATIO)
	VALUES(
    '食費',
    '3'
	);

INSERT INTO WISH_LIST (PRODUCT, PRICE,link)
VALUES ('キーボード',15000,'https://amzn.asia/d/1fJYgQr');

INSERT INTO INCOME (DATE,SALARY)
VALUES ('2023-04-05 13:33:23',50000);

UPDATE wish_list SET USER_ID = :user_id WHERE USER_ID IS NULL;

UPDATE INCOME SET USER_ID = '1111' WHERE USER_ID IS NULL;

